version: '3'
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    volumes:
      - type: volume
        source: img_db
        target: /app/app/data
volumes:
  img_db: